services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: myapp_user
      MYSQL_PASSWORD: userpassword
      volumes:
        -db_data:/var/lib/mysql/data


volumes:
  db_data:
